---
blank_issues_enabled: false
contact_links:
  - name: AH Technology Discord
    url: https://discord.com/invite/qkj62jt8Mg
    about: Please ask and answer questions here.
  - name: Security process
    url: https://www.aholddelhaize.com/security/
    about: Please report security vulnerabilities here.
