---
name: Evergreen
on:
  workflow_dispatch:
  schedule:
    - cron: "3 2 1 * *"

permissions:
  contents: read

jobs:
  evergreen:
    name: evergreen
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859  # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.OSPO_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OSPO_AUTOMATION_APP_KEY }}
      - name: Run evergreen action
        uses: github/evergreen@b4dd1856d07812548df00c72729206eb81f4c0a7  # 2.3.2
        env:
          GH_APP_ID: ${{ vars.OSPO_AUTOMATION_APP_ID }}
          GH_APP_INSTALLATION_ID: ${{ vars.OSPO_AUTOMATION_INSTALLATION_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.OSPO_AUTOMATION_APP_KEY }}
          ORGANIZATION: ${{ github.repository_owner }}
          SCHEDULE: monthly
          COMMIT_MESSAGE: "chore: add Dependabot configuration"
          TITLE: "chore: add Dependabot configuration"
          BODY: |
            This PR adds a Dependabot configuration file to the repository.
            This will enable Dependabot to keep your dependencies up-to-date automatically.
            For more information, see https://dependabot.com/
